from django.urls import path
from . import views
urlpatterns = [
   path('',views.home),
   path('view',views.vie, name = 'register'),
   path('offerlist/<str:mid>', views.offerlist, name = 'offerlist'),
   path('offerlist_in/<str:mid>/<str:temp>', views.offerlist_in, name = 'offerlist_in'),
   path('webeditpage/<str:mid>', views.webeditpage, name = 'webeditpage'),
   path('cheack', views.cheack, name = 'cheack'),
   path('update/<str:id>', views.update, name = 'update'),
   path('upload/<str:id>', views.upload, name = 'upload'),
   path('upload_first/<str:id>', views.upload_first, name = 'upload_first'),
   path('imupdate/<str:id>', views.imupdate, name = 'imupdate'),
   path('updatetable/<str:id>', views.updatetable, name = 'updatetable'),
   path('removtable/<str:id>', views.removtable, name = 'removtable'),
   path('resat/<str:id>', views.resat, name = 'resat'),
   path('restart/<str:id>', views.restart1, name = 'restart'),
   path('stop/<str:id>', views.stop, name = 'stop'),
   path('reload/<str:id>', views.reload1, name = 'reload'),
   path('registernew', views.registernew, name = 'registernew'),
   path('selectweb_type/<str:name>', views.selectweb_type, name = 'selectweb_type'),
   path('selecttemplate/<str:name>/<str:type1>', views.selecttemplate, name = 'selecttemplate'),
   path('view_template/<str:name>/<str:tmid>', views.view_template, name = 'view_template'),
   path('template_edit/<str:id>', views.template_edit, name = 'template_edit'),

   path('billing/<str:id>', views.billing, name = 'billing'),
   path('select_domain/<str:id>', views.select_domain, name = 'select_domain'),
   path('select_domain_remove/<str:id>', views.select_domain_remove, name = 'select_domain_remove'),
   path('payment/<str:id>', views.payment, name = 'payment'),
   path('dataentrypage/<str:id>', views.dataentrypage, name = 'dataentrypage'),
   path('register_email/<str:id>', views.register_email, name = 'register_email'),
   path('remove_email/<str:id>', views.remove_email, name = 'remove_email'),
   path('setup_promo/<str:id>', views.setup_promo, name = 'setup_promo'),
   path('remove_promo/<str:id>', views.remove_promo, name = 'remove_promo'),
   path('dataentrypage_main/<str:id>', views.dataentrypage_main, name = 'dataentrypage_main'),
   

   path('edit_page/<str:id>', views.edit_pages, name = 'edit_pages'),
   path('upload_first1/<str:id>', views.upload_first1, name = 'upload_first1'),
   path('domain_name/<str:id>', views.domain_name, name = 'domain_name'),
   path('domain_removemain/<str:id>', views.domain_removemain, name = 'domain_removemain'),
   path('domain_selected/<str:id>', views.domain_selec, name = 'domain_selected'),
   path('promotion/<str:id>', views.promotion, name = 'promotion'),
   path('livereport/<str:id>', views.livereport, name = 'livereport'),
   path('messages/<str:id>', views.messages, name = 'messages'),
]