# Generated by Django 3.2.6 on 2023-03-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_alter_vister_data_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vister_data',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
