# Generated by Django 3.2.6 on 2023-03-18 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0030_alter_webservice_unique_field'),
        ('promotion', '0004_vister_data_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='vister_data',
            name='ref',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='refral_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=500, null=True)),
                ('count', models.IntegerField(default=1)),
                ('rday', models.DateField(auto_now_add=True)),
                ('webservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice')),
            ],
        ),
        migrations.CreateModel(
            name='country_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=500, null=True)),
                ('count', models.IntegerField(default=1)),
                ('rday', models.DateField(auto_now_add=True)),
                ('webservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice')),
            ],
        ),
    ]
