# Generated by Django 3.2.6 on 2023-03-18 22:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0006_rename_country_country_data_cantry'),
    ]

    operations = [
        migrations.AddField(
            model_name='country_data',
            name='cun',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='vister_data',
            name='cun',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
