# Generated by Django 3.2.6 on 2023-02-26 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webuser', '0009_webservice_temp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='auto_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('account', models.CharField(max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='bank_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('account', models.CharField(max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='payment_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('descount', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('info', models.TextField(null=True)),
                ('paied', models.BooleanField(default=False)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.payment_type')),
                ('webservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice')),
            ],
        ),
        migrations.CreateModel(
            name='payed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('active_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('auto_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.auto_account')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.bank_account')),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment_request')),
            ],
        ),
        migrations.CreateModel(
            name='notification_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('info', models.TextField(null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payed')),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment_request')),
            ],
        ),
    ]
