# Generated by Django 3.2.6 on 2023-02-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request',
            name='total',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
    ]
