# Generated by Django 3.2.6 on 2023-02-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_request_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_request',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='payment_request',
            name='descount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='payment_request',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
