# Generated by Django 3.2.6 on 2023-02-27 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0010_webservice_template_type'),
        ('payment', '0004_auto_20230226_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_request_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('descount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('name', models.CharField(max_length=20, null=True)),
                ('info', models.TextField(null=True)),
                ('paied', models.BooleanField(default=False)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment_request')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.payment_type')),
                ('webservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice')),
            ],
        ),
    ]
