# Generated by Django 3.2.6 on 2023-02-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_request_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
