# Generated by Django 3.2.6 on 2023-03-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0013_auto_20230301_1306'),
        ('payment', '0006_payment_request_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request',
            name='domainname_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.domainname_selected'),
        ),
    ]
