# Generated by Django 3.2.6 on 2023-03-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0016_auto_20230303_1039'),
        ('payment', '0007_payment_request_domainname_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_request_item',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment_request_item',
            name='descount',
        ),
        migrations.AddField(
            model_name='payment_request_item',
            name='domainname_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.domainname_selected'),
        ),
        migrations.AddField(
            model_name='payment_request_item',
            name='promo_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.promo_selected'),
        ),
        migrations.AddField(
            model_name='payment_request_item',
            name='selected_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.selected_email'),
        ),
    ]
