# Generated by Django 3.2.6 on 2023-03-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20230303_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request_item',
            name='qunt',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
