# Generated by Django 3.2.6 on 2023-03-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20230303_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_request_item',
            old_name='payment',
            new_name='service_payment',
        ),
    ]
