# Generated by Django 3.2.6 on 2023-03-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_rename_payment_payment_request_item_service_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request_item',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
