# Generated by Django 3.2.6 on 2023-03-09 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20230309_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='wrong_paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('payment_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment_on')),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment_request')),
            ],
        ),
        migrations.RemoveField(
            model_name='notification_payment',
            name='payed',
        ),
        migrations.DeleteModel(
            name='payed',
        ),
    ]
