# Generated by Django 3.2.6 on 2023-03-09 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0021_webservice_paid'),
        ('payment', '0017_auto_20230309_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrong_paid',
            name='webservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice'),
        ),
    ]
