# Generated by Django 3.2.6 on 2023-01-24 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='webservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('port', models.CharField(max_length=20, null=True)),
                ('deploy', models.FileField(null=True, upload_to='file/deploy')),
                ('state', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('eday', models.DateTimeField(null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('web_templates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.web_templates')),
            ],
        ),
        migrations.CreateModel(
            name='webservice_template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Jsonfield', models.JSONField(null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('template_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.template_name')),
                ('webservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice')),
            ],
        ),
    ]
