# Generated by Django 3.2.6 on 2023-01-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0005_notiffication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notiffication',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
