# Generated by Django 3.2.6 on 2023-01-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0006_alter_notiffication_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservice',
            name='dname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webservice',
            name='sbdname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
