# Generated by Django 3.2.6 on 2023-01-30 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0007_auto_20230129_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='selected_add',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('stared', models.DateTimeField(null=True)),
                ('ended', models.DateTimeField(null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('add_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.add_type')),
                ('payment_way', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.payment_way')),
                ('webservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice')),
            ],
        ),
        migrations.CreateModel(
            name='add_payment_confermation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('payment_way', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.payment_way')),
                ('selected_add', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.selected_add')),
                ('webservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice')),
            ],
        ),
    ]
