# Generated by Django 3.2.6 on 2023-02-23 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20230223_1258'),
        ('webuser', '0008_add_payment_confermation_add_type_selected_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservice',
            name='temp_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.temp_type'),
        ),
    ]
