# Generated by Django 3.2.6 on 2023-02-27 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0010_webservice_template_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('eday', models.DateTimeField(null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('webservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice')),
            ],
        ),
    ]
