# Generated by Django 3.2.6 on 2023-02-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0011_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='domainname_found_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('info', models.TextField(null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('webservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice')),
            ],
        ),
        migrations.CreateModel(
            name='domainname_selected',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('info', models.TextField(null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('domainname_found_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.domainname_found_list')),
                ('webservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice')),
            ],
        ),
        migrations.CreateModel(
            name='domainname_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('webservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice')),
            ],
        ),
    ]
