# Generated by Django 3.2.6 on 2023-03-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0012_domainname_found_list_domainname_list_domainname_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('info', models.TextField(null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='domainname_found_list',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='domainname_list',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='selected_email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('info', models.TextField(null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('email_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.email_type')),
                ('webservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice')),
            ],
        ),
    ]
