# Generated by Django 3.2.6 on 2023-03-03 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0013_auto_20230301_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='promo_selected',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('info', models.TextField(null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='promo_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('info', models.TextField(null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='search_word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('promo_selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.promo_selected')),
                ('webservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice')),
            ],
        ),
        migrations.AddField(
            model_name='promo_selected',
            name='promo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.promo_type'),
        ),
        migrations.AddField(
            model_name='promo_selected',
            name='webservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice'),
        ),
    ]
