# Generated by Django 3.2.6 on 2023-03-03 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0014_auto_20230303_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='promo_service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('info', models.TextField(null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('promo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.promo_type')),
            ],
        ),
    ]
