# Generated by Django 3.2.6 on 2023-03-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0017_auto_20230303_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
