# Generated by Django 3.2.6 on 2023-03-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0019_domainname_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservice',
            name='active_pay',
            field=models.BooleanField(default=False),
        ),
    ]
