# Generated by Django 3.2.6 on 2023-03-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0020_webservice_active_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
