# Generated by Django 3.2.6 on 2023-03-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0021_webservice_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainname_selected',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='domainname_selected',
            name='info',
        ),
        migrations.RemoveField(
            model_name='domainname_selected',
            name='valid',
        ),
    ]
