# Generated by Django 3.2.6 on 2023-03-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0022_auto_20230311_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservice',
            name='unique_field',
            field=models.CharField(default='73e3e5911c974087adb8cdbeaaed4412', editable=False, max_length=32, unique=True),
        ),
    ]
