# Generated by Django 3.2.6 on 2023-03-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0024_alter_webservice_unique_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='unique_field',
            field=models.CharField(default='494981c25754449986e0b7dd0a5df0dc', editable=False, max_length=32, unique=True),
        ),
    ]
