# Generated by Django 3.2.6 on 2023-03-16 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0026_auto_20230315_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='unique_field',
            field=models.CharField(default='745839ba15a24c03a5b43edb4a42e84f', editable=False, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField(null=True)),
                ('rday', models.DateTimeField(auto_now_add=True)),
                ('webservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webuser.webservice')),
            ],
        ),
    ]
