# Generated by Django 3.2.6 on 2023-03-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0027_auto_20230316_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='unique_field',
            field=models.CharField(default='93604de0175148df9fde177a558c5964', editable=False, max_length=32, unique=True),
        ),
    ]
