# Generated by Django 3.2.6 on 2023-03-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0028_alter_webservice_unique_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='unique_field',
            field=models.CharField(default='3a6afc52686349d789bd1edd21fc1cf0', editable=False, max_length=32, unique=True),
        ),
    ]
