# Generated by Django 3.2.6 on 2023-03-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0029_alter_webservice_unique_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='unique_field',
            field=models.CharField(default='dd79ac7a8596473990cdde5d2c5120c5', editable=False, max_length=32, unique=True),
        ),
    ]
