# Generated by Django 3.2.6 on 2023-03-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0030_alter_webservice_unique_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='unique_field',
            field=models.CharField(default='579990d15fe84b3b915eabf75b9ec469', editable=False, max_length=32, unique=True),
        ),
    ]
