# Generated by Django 3.2.6 on 2023-03-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0032_alter_webservice_unique_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='unique_field',
            field=models.CharField(default='45b4e6bf3ba144f898af21f77f169312', editable=False, max_length=32, unique=True),
        ),
    ]
