# Generated by Django 3.2.6 on 2023-01-24 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='web_templates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('photo', models.FileField(null=True, upload_to='file/webimage')),
                ('deploy', models.FileField(null=True, upload_to='file/deploy')),
                ('show', models.FileField(null=True, upload_to='file/view')),
                ('code', models.CharField(max_length=20, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='template_name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('temp_name', models.CharField(max_length=20, null=True)),
                ('json_name', models.CharField(max_length=20, null=True)),
                ('web_templates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.web_templates')),
            ],
        ),
    ]
