# Generated by Django 3.2.6 on 2023-02-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20230208_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='temp_type',
            field=models.ManyToManyField(to='website.temp_type'),
        ),
    ]
