# Generated by Django 3.2.6 on 2023-02-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20230223_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_templates',
            name='temp_type',
            field=models.ManyToManyField(to='website.temp_type'),
        ),
    ]
