# Generated by Django 3.2.6 on 2023-02-25 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_web_templates_temp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='template_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('show', models.FileField(null=True, upload_to='file/view')),
                ('offer', models.JSONField(null=True)),
                ('web_templates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.web_templates')),
            ],
        ),
    ]
