# Generated by Django 3.2.6 on 2023-02-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_type',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
